xkbcommon: ERROR: failed to add default include path 
Qt: Failed to create XKB context!
Use QT_XKB_CONFIG_ROOT environmental variable to provide an additional search path, add ':' as separator to provide several search paths and/or make sure that XKB configuration data directory contains recent enough contents, to update please see http://cgit.freedesktop.org/xkeyboard-config/ .
slope [10.73450881]
intercept [-44.08906429]
Traceback (most recent call last):
  File "main.py", line 70, in <module>
    afaf
NameError: name 'afaf' is not defined
